name: Build

on:
  pull_request:
    paths:
      - '.github/workflows/build.yml'
      - 'cmd/**'
      - 'pkg/**'
      - 'test/**'
      - 'go.mod'
      - 'go.sum'
      - 'makefile'
      - '!**/*.md'
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Declare default permissions as read only.
permissions: read-all

jobs:
  ci:
    uses: Open-CMSIS-Pack/workflows-and-actions-collection/.github/workflows/build-and-verify.yml@build-verify-workflow
    with:
      program: cbuild
      build-matrix-goos: '["windows", "linux", "darwin"]'
      build-matrix-arch: '["amd64", "arm64"]'
      test-platform: '["ubuntu-24.04", "windows-2022", "macos-14"]'
      test-arch: '["amd64", "arm64"]'
      go-version-file: ./go.mod
      artifact-retention-days: 1
