name: markdown
on:
  pull_request:
    paths:
      - '.github/workflows/markdown.yml'
      - '.github/markdownlint.json'
      - '.github/markdownlint.jsonc'
      - '**/*.md'

permissions:
  contents: read

jobs:
  check:
    uses: soumeh01/infra-library/.github/workflows/markdown.yml@main
    with:
      lint-config: '.github/markdownlint.jsonc'
      link-check-config: '.github/markdown-link-check.jsonc'
