name: markdown
on:
  pull_request:
    paths:
      - '.github/workflows/markdown.yml'
      - '.github/markdownlint.json'
      - '.github/markdownlint.jsonc'
      - '**/*.md'

# Declare default permissions as read only.
permissions: read-all

jobs:
  linter:
    name: Lint markdown files
    runs-on: ubuntu-22.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Checkout devtools
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Register markdownlint warning matcher
        run: |
          echo "::add-matcher::.github/markdownlint.json"

      - name: Lint markdown files
        uses: avto-dev/markdown-lint@04d43ee9191307b50935a753da3b775ab695eceb # v1.5.0
        with:
          args: '**/*.md'
          config: '.github/markdownlint.jsonc'
          ignore: 'third_party_licenses.md'

      - name: Remove markdownlint warning matcher
        if: always()
        run: |
          echo "::remove-matcher owner=markdownlint::"

  check-links:
    name: Check markdown links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout devtools
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Check links
        uses: tcort/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'no'
          use-verbose-mode: 'yes'
          config-file: '.github/markdown-link-check.jsonc'
