name: Update vscode-workflows
on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-workflows:
    uses: Open-CMSIS-Pack/workflows-and-actions-collection/.github/workflows/update-workflows.yml@self-check
    secrets:
      TOKEN_ACCESS: ${{ secrets.PAT_TEST2 }}
